//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsBetting.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesMessagesException {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourcesMessagesException() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SportsBetting.Exceptions.ResourcesMessagesException", typeof(ResourcesMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }

        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        public static string NO_PERMISSION {
            get {
                return ResourceManager.GetString("NO_PERMISSION", resourceCulture);
            }
        }
        
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_ALREADY_EXISTS", resourceCulture);
            }
        }

        public static string AMOUNT_INVALID
        {
            get { return ResourceManager.GetString("AMOUNT_INVALID", resourceCulture); }
        }
        
        public static string WALLET_NOT_FOUND
        {
            get { return ResourceManager.GetString("WALLET_NOT_FOUND", resourceCulture); }
        }
        
        public static string BET_AMOUNT_GREATER_THAN_ZERO
        {
            get { return ResourceManager.GetString("BET_AMOUNT_GREATER_THAN_ZERO", resourceCulture); }
        }
        
        public static string BET_ODDS_INVALID
        {
            get { return ResourceManager.GetString("BET_ODDS_INVALID", resourceCulture); }
        }
        
        public static string BET_EVENT_NAME_REQUIRED
        {
            get { return ResourceManager.GetString("BET_EVENT_NAME_REQUIRED", resourceCulture); }
        }
        
        public static string BET_TYPE_REQUIRED
        {
            get { return ResourceManager.GetString("BET_TYPE_REQUIRED", resourceCulture); }
        }
        
        public static string INSUFFICIENT_BALANCE
        {
            get { return ResourceManager.GetString("INSUFFICIENT_BALANCE", resourceCulture); }
        }
        
        public static string FIXTURE_NOT_FOUND
        {
            get { return ResourceManager.GetString("FIXTURE_NOT_FOUND", resourceCulture); }
        }
        
        public static string BET_NOT_FOUND
        {
            get { return ResourceManager.GetString("BET_NOT_FOUND", resourceCulture); }
        }
        
        public static string CONCURRENT_BET_DETECTED
        {
            get { return ResourceManager.GetString("CONCURRENT_BET_DETECTED", resourceCulture); }
        }
         
        
    }
}
